import createClient from "openapi-fetch";
import type { paths } from "../types/api.generated"; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: "http://localhost:8080/",
});
