import type { User } from "../lib/userApi";

export const users: User[] = [
  {
    id: 1,
    username: "admin_master",
    email: "admin@example.com",
    role: "ADMIN",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-04-01"),
    isEnabled: true,
    authorities: ["ROLE_ADMIN", "ROLE_USER"],
  },
  {
    id: 2,
    username: "john_doe",
    email: "john@example.com",
    role: "USER",
    createdAt: new Date("2023-05-12"),
    updatedAt: new Date("2024-02-20"),
    isEnabled: true,
    authorities: ["ROLE_USER"],
  },
  {
    id: 3,
    username: "jane_smith",
    email: "jane@example.com",
    role: "USER",
    createdAt: new Date("2022-11-03"),
    updatedAt: new Date("2023-12-15"),
    isEnabled: false,
    authorities: ["ROLE_USER"],
  },
  {
    id: 4,
    username: "mod_mary",
    email: "mary@example.com",
    role: "MODERATOR",
    createdAt: new Date("2023-03-08"),
    updatedAt: new Date("2024-03-01"),
    isEnabled: true,
    authorities: ["ROLE_MODERATOR", "ROLE_USER"],
  },
  {
    id: 5,
    username: "guest123",
    email: "guest123@example.com",
    role: "GUEST",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-04-10"),
    isEnabled: false,
    authorities: [],
  },
  {
    id: 6,
    username: "susan_lee",
    email: "susan@example.com",
    role: "USER",
    createdAt: new Date("2022-09-21"),
    updatedAt: new Date("2024-01-01"),
    isEnabled: true,
    authorities: ["ROLE_USER"],
  },
  {
    id: 7,
    username: "dev_dan",
    email: "dan@example.com",
    role: "DEVELOPER",
    createdAt: new Date("2021-12-11"),
    updatedAt: new Date("2024-03-21"),
    isEnabled: true,
    authorities: ["ROLE_DEVELOPER", "ROLE_USER"],
  },
  {
    id: 8,
    username: "charlie_p",
    email: "charlie@example.com",
    role: "USER",
    createdAt: new Date("2022-06-18"),
    updatedAt: new Date("2023-08-25"),
    isEnabled: false,
    authorities: ["ROLE_USER"],
  },
  {
    id: 9,
    username: "amy_williams",
    email: "amy@example.com",
    role: "USER",
    createdAt: new Date("2023-02-14"),
    updatedAt: new Date("2024-02-15"),
    isEnabled: true,
    authorities: ["ROLE_USER"],
  },
  {
    id: 10,
    username: "tester_bot",
    email: "tester@example.com",
    role: "BOT",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-04-01"),
    isEnabled: true,
    authorities: ["ROLE_BOT"],
  },
];

export const getUsers = (): User[] => {
  return users;
};
